import Image from "next/image";
import Link from "next/link";
import { SocialLinks } from "@/components/social-links";

const links=[
  {title:"Colegio",items:[["Institucional","/institucional"],["Dictámenes","/dictamenes"],["Novedades","/novedades"],["Contacto","/contacto"]]},
  {title:"Profesionales",items:[["Trámites","/tramites"],["Matriculados","/matriculados"],["Nomenclador","/nomenclador"],["Becas","/becas"]]},
  {title:"Formación",items:[["Actividad académica","/actividad-academica"],["Biblioteca","/biblioteca"]]},
];
export function SiteFooter(){return <footer className="mt-auto bg-cpe-royal text-white"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-12"><div className="grid gap-10 lg:grid-cols-[1.3fr_2fr]"><div><Image src="/logo_final.png" alt="CPE Santa Fe" width={885} height={256} className="h-24 w-auto object-contain"/><p className="mt-4 max-w-sm text-xs leading-5 text-white/70">Colegio de Profesionales en Enfermería de Santa Fe. Acompañamos y jerarquizamos el ejercicio profesional en toda la provincia.</p><a href="https://cpesag.com.ar" target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-full bg-cpe-navy px-4 py-2 text-xs font-bold transition hover:bg-white hover:text-cpe-navy">Ingresar al SAG ↗</a><SocialLinks className="mt-6 text-white" /></div><div className="grid gap-6 sm:grid-cols-3">{links.map(col=><div key={col.title}><p className="text-[11px] font-bold uppercase tracking-[.14em] text-cpe-mint">{col.title}</p><ul className="mt-3 space-y-1.5">{col.items.map(([label,href])=><li key={href}><Link href={href} className="text-xs text-white/65 transition hover:text-white">{label}</Link></li>)}</ul></div>)}</div></div><div className="mt-10 flex flex-col gap-4 border-t border-white/10 pt-5 text-xs text-white/40 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} CPE Santa Fe. Todos los derechos reservados.</p><p>Corrientes 2976 · Santa Fe · (0342) 4598561</p><a href="https://kubbo.com.ar" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-white/40 transition hover:text-white/70">Desarrollado por <Image src="/logo_verde.png" alt="Kubbo" width={1767} height={631} className="h-4 w-auto object-contain" /></a></div></div></footer>}
